import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import  ThemeProvider  from "@/providers/ThemeProvider"
import { cookies } from 'next/headers'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cookieStore = cookies()
  const theme = cookieStore.get('theme')?.value || 'system' // fallback

export default function RootLayout({ children }) {
  return (
    const cookieStore = cookies()
  const theme = cookieStore.get('theme')?.value || 'system' // fallback
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
